# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Warpen.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1020, 866)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 1021, 821))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 10, -1, 5)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnSetPointPic1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnSetPointPic1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btnSetPointPic1.setObjectName("btnSetPointPic1")
        self.horizontalLayout_4.addWidget(self.btnSetPointPic1)
        self.btnLodePic2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnLodePic2.setMaximumSize(QtCore.QSize(100, 32))
        self.btnLodePic2.setObjectName("btnLodePic2")
        self.horizontalLayout_4.addWidget(self.btnLodePic2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnLodePic1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnLodePic1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnLodePic1.setObjectName("btnLodePic1")
        self.horizontalLayout_5.addWidget(self.btnLodePic1)
        self.btnSetPointPic2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnSetPointPic2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btnSetPointPic2.setObjectName("btnSetPointPic2")
        self.horizontalLayout_5.addWidget(self.btnSetPointPic2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plot1 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.plot1.setMinimumSize(QtCore.QSize(400, 0))
        self.plot1.setObjectName("plot1")
        self.horizontalLayout.addWidget(self.plot1)
        self.plot2 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.plot2.setMinimumSize(QtCore.QSize(400, 0))
        self.plot2.setObjectName("plot2")
        self.horizontalLayout.addWidget(self.plot2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.openGLWidget_3 = QtWidgets.QOpenGLWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openGLWidget_3.sizePolicy().hasHeightForWidth())
        self.openGLWidget_3.setSizePolicy(sizePolicy)
        self.openGLWidget_3.setMinimumSize(QtCore.QSize(0, 200))
        self.openGLWidget_3.setObjectName("openGLWidget_3")
        self.verticalLayout_2.addWidget(self.openGLWidget_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(80, 30, 841, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(400, 0))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(120, 60, 116, 37))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnCalc = QtWidgets.QPushButton(self.groupBox)
        self.btnCalc.setObjectName("btnCalc")
        self.horizontalLayout_3.addWidget(self.btnCalc)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.scal = QtWidgets.QLineEdit(self.groupBox)
        self.scal.setObjectName("scal")
        self.horizontalLayout_3.addWidget(self.scal)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.rot = QtWidgets.QLineEdit(self.groupBox)
        self.rot.setObjectName("rot")
        self.horizontalLayout_3.addWidget(self.rot)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.trans = QtWidgets.QLineEdit(self.groupBox)
        self.trans.setObjectName("trans")
        self.horizontalLayout_3.addWidget(self.trans)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnSetPointPic1.setText(_translate("Form", "Clear Poins"))
        self.btnLodePic2.setText(_translate("Form", "Lode Pic "))
        self.btnLodePic1.setText(_translate("Form", "Lode Pic "))
        self.btnSetPointPic2.setText(_translate("Form", "Clear Poins"))
        self.groupBox_2.setTitle(_translate("Form", "GroupBox"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.btnCalc.setText(_translate("Form", "Calc"))
        self.label.setText(_translate("Form", "Scale"))
        self.label_2.setText(_translate("Form", "Rot"))
        self.label_3.setText(_translate("Form", "Trans"))
