# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1408, 707)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1353, 651))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, 5)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnLoadImage1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoadImage1.sizePolicy().hasHeightForWidth())
        self.btnLoadImage1.setSizePolicy(sizePolicy)
        self.btnLoadImage1.setMaximumSize(QtCore.QSize(120, 32))
        self.btnLoadImage1.setObjectName("btnLoadImage1")
        self.verticalLayout_3.addWidget(self.btnLoadImage1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnWarp = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnWarp.sizePolicy().hasHeightForWidth())
        self.btnWarp.setSizePolicy(sizePolicy)
        self.btnWarp.setMinimumSize(QtCore.QSize(100, 0))
        self.btnWarp.setObjectName("btnWarp")
        self.verticalLayout_4.addWidget(self.btnWarp)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btnLoadImage2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnLoadImage2.setMaximumSize(QtCore.QSize(120, 37))
        self.btnLoadImage2.setObjectName("btnLoadImage2")
        self.verticalLayout_6.addWidget(self.btnLoadImage2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_5.addWidget(self.pushButton_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 7, 1, 1)
        self.frames = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frames.sizePolicy().hasHeightForWidth())
        self.frames.setSizePolicy(sizePolicy)
        self.frames.setMaximumSize(QtCore.QSize(30, 16777215))
        self.frames.setMaxLength(10)
        self.frames.setObjectName("frames")
        self.gridLayout.addWidget(self.frames, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plot1 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.plot1.setMinimumSize(QtCore.QSize(400, 0))
        self.plot1.setMaximumSize(QtCore.QSize(506, 280))
        self.plot1.setMouseTracking(True)
        self.plot1.setObjectName("plot1")
        self.horizontalLayout.addWidget(self.plot1)
        self.plot2 = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot2.sizePolicy().hasHeightForWidth())
        self.plot2.setSizePolicy(sizePolicy)
        self.plot2.setMinimumSize(QtCore.QSize(400, 0))
        self.plot2.setMaximumSize(QtCore.QSize(505, 280))
        self.plot2.setMouseTracking(True)
        self.plot2.setObjectName("plot2")
        self.horizontalLayout.addWidget(self.plot2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.plot3 = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot3.sizePolicy().hasHeightForWidth())
        self.plot3.setSizePolicy(sizePolicy)
        self.plot3.setMinimumSize(QtCore.QSize(1019, 200))
        self.plot3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.plot3.setMouseTracking(True)
        self.plot3.setObjectName("plot3")
        self.verticalLayout.addWidget(self.plot3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1408, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.loadImage1 = QtWidgets.QAction(MainWindow)
        self.loadImage1.setObjectName("loadImage1")
        self.loadImage2 = QtWidgets.QAction(MainWindow)
        self.loadImage2.setObjectName("loadImage2")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.loadImage1)
        self.menuFile.addAction(self.loadImage2)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.btnLoadImage2.clicked.connect(self.loadImage2.trigger)
        self.btnLoadImage1.clicked.connect(self.loadImage1.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Frames"))
        self.btnLoadImage1.setText(_translate("MainWindow", "Load Image"))
        self.btnWarp.setText(_translate("MainWindow", "Warp"))
        self.btnLoadImage2.setText(_translate("MainWindow", "Load Image"))
        self.pushButton_3.setText(_translate("MainWindow", "Triangulate"))
        self.frames.setText(_translate("MainWindow", "30"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.loadImage1.setText(_translate("MainWindow", "Load (Image 1)"))
        self.loadImage2.setText(_translate("MainWindow", "Load (Image 2)"))
